name: Build Docker

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  workflow_dispatch:

env:
  # Use docker.io for Docker Hub if empty
  GHCR: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.actor }}/avorion


jobs:
  stable:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Collect version from Avorion dedicated server executable
      - name: Get version
        id: version
        uses: addnab/docker-run-action@v3
        with:
          image: cm2network/steamcmd:steam
          run: |
            "${STEAMCMDDIR}/steamcmd.sh" +force_install_dir /home/steam/avorion-dedicated +login anonymous +app_update 565060 validate +quit
            echo "::set-output name=version::$(/home/steam/avorion-dedicated/bin/AvorionServer --version)"

      - name: Search for Tag
        id: tag
        run: |
          tag=$(git tag -l "v${{ steps.version.outputs.version }}")
          echo "Tag: ${tag}"
          if [ "$tag" == "v${{ steps.version.outputs.version }}" ]; then
            echo "Version exists"
            echo "::set-output name=exists::true"
          else
            echo "Version does not exist"
            echo "::set-output name=exists::false"
          fi


      # Generate Docker Metadata
      - name: Docker meta
        id: meta
        if: ${{ steps.tag.outputs.exists }} == false
        uses: docker/metadata-action@v4
        with:
          # list of Docker images to use as base name for tags
          images: |
            ${{ env.GHCR }}/${{ env.IMAGE_NAME }}
          # generate Docker tags based on the following events/attributes
          tags: |
            type=raw,value=${{ steps.version.outputs.version }}
            type=raw,value=stable
            type=raw,value=latest

      # Login against a Docker registry
      # https://github.com/docker/login-action
      - name: Log into registry ${{ env.REGISTRY }}
        if: ${{ steps.tag.outputs.exists }} == false
        uses: docker/login-action@v2
        with:
          registry: ${{ env.GHCR }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build and push Docker image with Buildx (don't push on PR)
      # https://github.com/docker/build-push-action
      - name: Set up Docker Buildx
        if: ${{ steps.tag.outputs.exists }} == false
        uses: docker/setup-buildx-action@v2

      - name: Build and push Docker image
        if: ${{ steps.tag.outputs.exists }} == false
        id: build-and-push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            INSTALL_ARGS=""

      # Create tag for version
      # https://github.com/mathieudutour/github-tag-action
      - name: Tag Version
        if: ${{ steps.tag.outputs.exists }} == false
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_bump: false
          custom_tag: ${{ steps.version.outputs.version }}
